limits:
  max_rounds: 64
  max_bytes_per_message: 256
  max_total_bytes: 3072

systems:
  certtalk:
    max_path_attempts: 6
    max_path_length: 64
    compact_schema: true
  sendall:
    compact_schema: true
    chunk_size: 32
  greedyprobe:
    compact_schema: true
    max_probes: 12
  cutgrow:
    compact_schema: true
  respondermincut:
    compact_schema: true
    max_iterations: 12
